CodeIgniter.php
const CI_VERSION
const CI_CORE
if (method_exists($CI, '_remap')) else
if (!is_php('5.3')) if (isset($assign_to_config['subclass_prefix']) AND $assign_to_config['subclass_prefix']!= '') if (function_exists("set_time_limit")==TRUE AND @ini_get("safe_mode")==0) $BM
Referenced by CI_Output\_display.
$EXT
$CFG
Referenced by CI_Hooks\_initialize, CI_Output\_display, CI_Output\_display_cache, CI_Utf8\__construct.
if (isset($assign_to_config)) $UNI
Referenced by CI_Input\__construct.
$URI
Referenced by CI_Output\_display_cache.
$RTR
if (isset($routing)) $OUT
if ($EXT->_call_hook('cache_override')===FALSE) $SEC
Referenced by CI_Input\__construct.
$IN
$LANG
Referenced by CI_DB_driver\display_error.
if (file_exists(APPPATH.'core/'.$CFG->config['subclass_prefix'].'Controller.php')) if(!file_exists(APPPATH.'controllers/'.$RTR->fetch_directory().$RTR->fetch_class().'.php'))(!file_exists(APPPATH.'controllers/'.$RTR->fetch_directory().$RTR->fetch_class().'.php'))
$class
Referenced by CI_Hooks\_run_hook, CI_Migration\version, CI_Controller\__construct, CI_Loader\is_loaded, CI_Loader\library, CI_Loader\dbutil, CI_Loader\dbforge, CI_Loader\_ci_load_class, CI_Loader\_ci_init_class, CI_Driver_Library\__get, CI_Javascript\addClass, CI_Javascript\removeClass, CI_Javascript\toggleClass, CI_Jquery\_zebraTables.
$method
Referenced by CI_Migration\version, CI_Profiler\set_sections, MY_Model\get, CI_Driver\decorate, CI_Driver\__call, CI_Email\initialize, CI_Upload\initialize.
$CI
Referenced by CI_Loader\model, CI_Loader\database, CI_Loader\dbutil, CI_Loader\dbforge, CI_Loader\language, CI_Loader\config, CI_Loader\_ci_load_class, CI_Loader\_ci_init_class, CI_Loader\_ci_get_component, CI_Model\__get, CI_Output\_display, CI_Output\_write_cache, CI_DB_forge\__construct, CI_DB_utility\__construct, CI_DB_utility\xml_from_result, CI_DB_utility\backup, CI_Cache_file\__construct, CI_Email\_set_error_message, CI_FTP\_error, CI_Image_lib\set_error, CI_Pagination\create_links, CI_Parser\parse, CI_Parser\_parse, CI_Unit_test\report, CI_Unit_test\result, CI_Upload\do_xss_clean, CI_Upload\set_error, XML_RPC_Response\decode, XML_RPC_Message\output_parameters, CI_Xmlrpcs\_execute, CI_Zip\download.
& get_instance()
References CI_Controller\get_instance.
Referenced by CI_Migration\__get, CI_Profiler\__construct, CI_Lang\load, CI_Loader\model, CI_Loader\database, CI_Loader\dbutil, CI_Loader\dbforge, CI_Loader\language, CI_Loader\config, CI_Loader\_ci_load, CI_Loader\_ci_load_class, CI_Loader\_ci_init_class, CI_Loader\_ci_get_component, CI_Model\__get, CI_Output\_display, CI_Output\_write_cache, CI_DB_Cache\__construct, CI_DB_forge\__construct, CI_DB_utility\__construct, CI_DB_utility\xml_from_result, CI_DB_utility\backup, CI_Cache_file\__construct, CI_Calendar\__construct, CI_Cart\__construct, CI_Driver_Library\__get, CI_Email\_set_error_message, CI_Encrypt\__construct, CI_Encrypt\get_key, CI_Form_validation\__construct, CI_FTP\_error, CI_Image_lib\set_error, CI_Javascript\__construct, CI_Jquery\__construct, CI_Pagination\create_links, CI_Parser\parse, CI_Parser\_parse, CI_Session\__construct, CI_Unit_test\report, CI_Unit_test\result, CI_Upload\do_xss_clean, CI_Upload\set_error, XML_RPC_Response\decode, XML_RPC_Message\output_parameters, CI_Xmlrpcs\_execute, CI_Zip\download.