CI_DB_driver
$username
$password
$hostname
$database
$dbdriver
Referenced by platform.
$dbprefix
$char_set
$dbcollat
$autoinit
$swap_pre
$port
$pconnect
$conn_id
Referenced by query.
$result_id
Referenced by query.
$db_debug
$benchmark
$query_count
Referenced by total_queries.
$bind_marker
$save_queries
$queries
$query_times
$data_cache
$trans_enabled
$trans_strict
$_trans_depth
$_trans_status
Referenced by trans_status.
$cache_on
$cachedir
$cache_autodel
$CACHE
$_protect_identifiers
Referenced by CI_DB_active_record\_where, _protect_identifiers.
$_reserved_identifiers
$stmt_id
Referenced by query.
$curs_id
$limit_used
Referenced by query.
__construct($params)
Constructor. Accepts one parameter containing the database connection settings. array
initialize()
Initialize Database Settingsprivate Called by the constructor mixed void
References display_error, db_set_charset.
Referenced by simple_query.
db_set_charset($charset, $collation)
Set client character setpublic string string resource
References display_error.
Referenced by initialize.
platform()
The name of the platform in use (mysql, mssql, etc...)public string
References $dbdriver.
version()
Database Version Number. Returns a string containing the version of the database being usedpublic string
References display_error, query.
query($sql, $binds=FALSE, $return_object=TRUE)
Execute the queryAccepts an SQL string as input and returns a result object upon successful execution of a "read" type query. Returns boolean TRUE upon successful execution of a "write" type query. Returns boolean FALSE upon failure, and if the $db_debug variable is set to TRUE will raise an error.public string An SQL query string array An array of binding data mixed
References display_error, compile_binds, cache_on, _cache_init, load_rdriver, simple_query, trans_complete, is_write_type, $conn_id, $result_id, $stmt_id, $limit_used.
Referenced by CI_DB_active_record\get, CI_DB_active_record\count_all_results, CI_DB_active_record\get_where, CI_DB_active_record\insert_batch, CI_DB_active_record\insert, CI_DB_active_record\replace, CI_DB_active_record\update, CI_DB_active_record\update_batch, CI_DB_active_record\empty_table, CI_DB_active_record\truncate, CI_DB_active_record\delete, version, list_tables, list_fields, field_data.
load_rdriver()
Load the result driverspublic string the name of the result class
References BASEPATH.
Referenced by query.
simple_query($sql)
Simple Query This is a simplified version of the query() function. Internally we only use it when running transaction commands since they do not require all the features of the main query() function.public string the sql query mixed
References initialize.
Referenced by query.
trans_off()
Disable Transactions This permits transactions to be disabled at run-time.public void
trans_strict($mode=TRUE)
Enable/disable Transaction Strict Mode When strict mode is enabled, if you are running multiple groups of transactions, if one group fails all groups will be rolled back. If strict mode is disabled, each group is treated autonomously, meaning a failure of one group will not affect any otherspublic void
Referenced by trans_complete.
trans_start($test_mode=FALSE)
Start Transactionpublic void
trans_complete()
Complete Transactionpublic bool
References trans_strict.
Referenced by query.
trans_status()
Lets you retrieve the transaction flag to determine if it has failedpublic bool
References $_trans_status.
compile_binds($sql, $binds)
Compile Bindingspublic string the sql statement array an array of bind data string
References escape.
Referenced by query.
is_write_type($sql)
Determines if a query is a "write" type.public string An SQL query string boolean
Referenced by query.
elapsed_time($decimals=6)
Calculate the aggregate query elapsed timepublic integer The number of decimal places integer
total_queries()
Returns the total number of queriespublic integer
References $query_count.
last_query()
Returns the last query that was executedpublic void
escape($str)
"Smart" Escape StringEscapes data based on type Sets boolean and null typespublic string mixed
Referenced by CI_DB_active_record\_where_in, CI_DB_active_record\set, CI_DB_active_record\set_insert_batch, CI_DB_active_record\set_update_batch, compile_binds, insert_string, update_string.
escape_like_str($str)
Escape LIKE StringCalls the individual driver for platform specific escaping for LIKE conditionspublic string mixed
Referenced by CI_DB_active_record\_like.
primary($table= '')
PrimaryRetrieves the primary key. It assumes that the row in the first position is the primary keypublic string the table name string
References list_fields.
list_tables($constrain_by_prefix=FALSE)
Returns an array of table namespublic array
References display_error, query.
Referenced by table_exists.
table_exists($table_name)
Determine if a particular table exists public boolean
References _protect_identifiers, list_tables.
list_fields($table= '')
Fetch MySQL Field Namespublic string the table name array
References display_error, query.
Referenced by primary, field_exists.
field_exists($field_name, $table_name)
Determine if a particular field exists public string string boolean
References list_fields.
field_data($table= '')
Returns an object with field datapublic string the table name object
References display_error, query, _protect_identifiers.
insert_string($table, $data)
Generate an insert stringpublic string the table upon which the query will be performed array an associative array data of key/values string
References escape, _protect_identifiers.
update_string($table, $data, $where)
Generate an update stringpublic string the table upon which the query will be performed array an associative array data of key/values mixed the "where" statement string
References _protect_identifiers, escape, _has_operator.
_has_operator($str)
Tests whether the string has an SQL operatorprivate string bool
Referenced by CI_DB_active_record\_where, CI_DB_active_record\_having, update_string.
call_function($function)
Enables a native PHP function to be run, using a platform agnostic wrapper.public string the function name mixed any parameters needed by the function mixed
References if, display_error.
cache_set_path($path= '')
Set Cache Directory Pathpublic string the path to the cache directory void
cache_on()
Enable Query Cachingpublic void
Referenced by query, cache_off.
cache_off()
Disable Query Cachingpublic void
References cache_on.
Referenced by _cache_init.
cache_delete($segment_one= '', $segment_two= '')
Delete the cache files associated with a particular URIpublic void
References _cache_init.
cache_delete_all()
Delete All cache filespublic void
References _cache_init.
_cache_init()
Initialize the Cache Classprivate void
References BASEPATH, cache_off.
Referenced by query, cache_delete, cache_delete_all.
close()
Close DB Connectionpublic void
display_error($error= '', $swap= '', $native=FALSE)
Display an error messagepublic string the error message string any "swap" values boolean whether to localize the message string sends the application/error_db.php template
References $LANG, BASEPATH.
Referenced by CI_DB_active_record\_max_min_avg_sum, CI_DB_active_record\insert_batch, CI_DB_active_record\insert, CI_DB_active_record\replace, CI_DB_active_record\update, CI_DB_active_record\update_batch, CI_DB_active_record\set_update_batch, CI_DB_active_record\empty_table, CI_DB_active_record\truncate, CI_DB_active_record\delete, CI_DB_active_record\dbprefix, initialize, db_set_charset, version, query, list_tables, list_fields, field_data, call_function.
protect_identifiers($item, $prefix_single=FALSE)
Protect IdentifiersThis function adds backticks if appropriate based on db typeprivate mixed the item to escape mixed the item with backticks
References _protect_identifiers.
_protect_identifiers($item, $prefix_single=FALSE, $protect_identifiers=NULL, $field_exists=TRUE)
Protect IdentifiersThis function is used extensively by the Active Record class, and by a couple functions in this class. It takes a column or table name (optionally with an alias) and inserts the table prefix onto it. Some logic is necessary in order to deal with column names that include the path. Consider a query like this:SELECT * FROM hostname.database.table.column AS c FROM hostname.database.tableOr a query with aliasing:SELECT m.member_id, m.member_name FROM members AS mSince the column name can include up to four segments (host, DB, table, column) or also have an alias prefix, we need to do a bit of work to figure this out and insert the table prefix (if it exists) in the proper position, and escape only the correct identifiers.private string bool mixed bool string
References $_protect_identifiers.
Referenced by CI_DB_active_record\_max_min_avg_sum, CI_DB_active_record\from, CI_DB_active_record\join, CI_DB_active_record\_where, CI_DB_active_record\_where_in, CI_DB_active_record\_like, CI_DB_active_record\group_by, CI_DB_active_record\_having, CI_DB_active_record\order_by, CI_DB_active_record\set, CI_DB_active_record\count_all_results, CI_DB_active_record\insert_batch, CI_DB_active_record\set_insert_batch, CI_DB_active_record\insert, CI_DB_active_record\replace, CI_DB_active_record\update, CI_DB_active_record\update_batch, CI_DB_active_record\set_update_batch, CI_DB_active_record\empty_table, CI_DB_active_record\truncate, CI_DB_active_record\delete, CI_DB_active_record\_compile_select, CI_DB_active_record\_merge_cache, table_exists, field_data, insert_string, update_string, protect_identifiers.
_reset_select()
Dummy method that allows Active Record class to be disabledThis function is used extensively by every db driver.void