CI_Input
$ip_address
Referenced by ip_address.
$user_agent
Referenced by user_agent.
$_allow_get_array
$_standardize_newlines
$_enable_xss
$_enable_csrf
$headers
Referenced by request_headers.
__construct()
ConstructorSets whether to globally enable the XSS processing and whether to allow the $_GET arrayvoid
References $SEC, $UNI, _sanitize_globals.
_fetch_from_array(&$array, $index= '', $xss_clean=FALSE)
Fetch from arrayThis is a helper function to retrieve values from global arraysprivate array string bool string
Referenced by get, post, cookie, server, request_headers.
get($index=NULL, $xss_clean=FALSE)
Fetch an item from the GET arraypublic string bool string
References _fetch_from_array.
post($index=NULL, $xss_clean=FALSE)
Fetch an item from the POST arraypublic string bool string
References _fetch_from_array.
Referenced by get_post.
get_post($index= '', $xss_clean=FALSE)
Fetch an item from either the GET array or the POSTpublic string The index key bool XSS cleaning string
References post.
cookie($index= '', $xss_clean=FALSE)
Fetch an item from the COOKIE arraypublic string bool string
References _fetch_from_array.
set_cookie($name= '', $value= '', $expire= '', $domain= '', $path= '/', $prefix= '', $secure=FALSE)
Set cookieAccepts six parameter, or you can submit an associative array in the first parameter containing all the values.public mixed string the value of the cookie string the number of seconds until expiration string the cookie domain. Usually: .yourdomain.com string the cookie path string the cookie prefix bool true makes the cookie secure void
server($index= '', $xss_clean=FALSE)
Fetch an item from the SERVER arraypublic string bool string
References _fetch_from_array.
Referenced by ip_address, is_ajax_request.
ip_address()
Fetch the IP Addressstring
References $ip_address, server, valid_ip.
valid_ip($ip, $which= '')
Validate IP Addresspublic string string ipv4 or ipv6 bool
Referenced by ip_address.
user_agent()
User Agentpublic string
References $user_agent.
_sanitize_globals()
Sanitize GlobalsThis function does the following:Unsets $_GET data (if query strings are not enabled)Unsets all globals if register_globals is enabledStandardizes newline characters to private void
References _clean_input_keys, _clean_input_data, is_cli_request.
Referenced by __construct.
_clean_input_data($str)
Clean Input DataThis is a helper function. It escapes data and standardizes newline characters to private string string
References _clean_input_keys.
Referenced by _sanitize_globals.
_clean_input_keys($str)
Clean KeysThis is a helper function. To prevent malicious users from trying to exploit keys we make sure that keys are only named with alpha-numeric text and a few other items.private string string
Referenced by _sanitize_globals, _clean_input_data.
request_headers($xss_clean=FALSE)
Request HeadersIn Apache, you can simply call apache_request_headers(), however for people running other webservers the function is undefined. bool XSS cleaning array
References $headers, _fetch_from_array.
Referenced by get_request_header.
get_request_header($index, $xss_clean=FALSE)
Get Request HeaderReturns the value of a single member of the headers class member string array key for $this->headers boolean XSS Clean or not mixed FALSE on failure, string on success
References request_headers.
is_ajax_request()
Is ajax Request?Test to see if a request contains the HTTP_X_REQUESTED_WITH headerboolean
References server.
is_cli_request()
Is cli Request?Test to see if a request was made from the command linebool
Referenced by _sanitize_globals.
_valid_ipv4($ip)
Validate IPv4 AddressUpdated version suggested by Geert De Deckereprotected string bool
Referenced by _valid_ipv6.
_valid_ipv6($str)
Validate IPv6 Addressprotected string bool
References _valid_ipv4.