CI_Unit_test
$active
$results
Referenced by result.
$strict
$_template
$_template_rows
Referenced by report.
$_test_items_visible
__construct()
set_test_items($items=array())
Run the testsRuns the supplied testspublic array void
run($test, $expected=TRUE, $test_name= 'undefined', $notes= '')
Run the testsRuns the supplied testspublic mixed mixed string string
References active, _backtrace, report, result.
report($result=array())
Generate a reportDisplays a table with the test datapublic string
References result, $CI, get_instance, _parse_template, $_template_rows.
Referenced by run.
use_strict($state=TRUE)
Use strict comparisonCauses the evaluation to use === rather than ==public bool null
active($state=TRUE)
Make Unit testing activeEnables/disables unit testingpublic bool null
Referenced by run.
result($results=array())
Result ArrayReturns the raw result datapublic array
References $CI, get_instance, $results.
Referenced by run, report.
set_template($template)
Set the templateThis lets us set the template to be used to display resultspublic string void
_backtrace()
Generate a backtraceThis lets us show file names and line numbersprivate array
Referenced by run.
_default_template()
Get Default Templateprivate string
Referenced by _parse_template.
_parse_template()
Parse TemplateHarvests the data within the template {pseudo-variables}private void
References _default_template.
Referenced by report.