CI_FTP
$hostname
$username
$password
$port
$passive
$debug
$conn_id
__construct($config=array())
Constructor - Sets PreferencesThe constructor can be passed an array of config values
References $config, initialize.
initialize($config=array())
Initialize preferencespublic array void
References $config.
Referenced by __construct, connect.
connect($config=array())
FTP Connectpublic array the connection values bool
References $config, initialize, _error, _login.
_login()
FTP Loginprivate bool
Referenced by connect.
_is_conn()
Validates the connection IDprivate bool
References _error.
Referenced by changedir, mkdir, upload, download, rename, delete_file, delete_dir, chmod, list_files, mirror, close.
changedir($path= '', $supress_debug=FALSE)
Change directoryThe second parameter lets us momentarily turn off debugging so that this function can be used to test for the existence of a folder without throwing an error. There's no FTP equivalent to is_dir() so we do it by trying to change to a particular directory. Internally, this parameter is only used by the "mirror" function below.public string bool bool
References _is_conn, _error.
Referenced by mirror.
mkdir($path= '', $permissions=NULL)
Create a directorypublic string bool
References _is_conn, _error, chmod.
Referenced by mirror.
upload($locpath, $rempath, $mode= 'auto', $permissions=NULL)
Upload a file to the serverpublic string string string bool
References _is_conn, _error, _getext, _settype, chmod.
Referenced by mirror.
download($rempath, $locpath, $mode= 'auto')
Download a file from a remote server to the local serverpublic string string string bool
References _is_conn, _getext, _settype, _error.
rename($old_file, $new_file, $move=FALSE)
Rename (or move) a filepublic string string bool bool
References _is_conn, _error.
Referenced by move.
move($old_file, $new_file)
Move a filepublic string string bool
References rename.
delete_file($filepath)
Rename (or move) a filepublic string bool
References _is_conn, _error.
delete_dir($filepath)
Delete a folder and recursively delete everything (including sub-folders) containted within it.public string bool
References _is_conn, list_files, _error.
chmod($path, $perm)
Set file permissionspublic string the file path string the permissions bool
References _is_conn, _error.
Referenced by mkdir, upload.
list_files($path= '.')
FTP List files in the specified directorypublic array
References _is_conn.
Referenced by delete_dir.
mirror($locpath, $rempath)
Read a directory and recreate it remotelyThis function recursively reads a folder and everything it contains (including sub-folders) and creates a mirror via FTP based on it. Whatever the directory structure of the original file path will be recreated on the server.public string path to source with trailing slash string path to destination - include the base folder with trailing slash bool
References _is_conn, changedir, mkdir, _getext, _settype, upload.
_getext($filename)
Extract the file extensionprivate string string
Referenced by upload, download, mirror.
_settype($ext)
Set the upload typeprivate string string
Referenced by upload, download, mirror.
close()
Close the connectionpublic string path to source string path to destination bool
References _is_conn.
_error($line)
Display error messageprivate string bool
References $CI, get_instance.
Referenced by connect, _is_conn, changedir, mkdir, upload, download, rename, delete_file, delete_dir, chmod.