CI_Router
$config
$routes
$error_routes
$class
Referenced by fetch_class.
$method
Referenced by set_method, fetch_method.
$directory
Referenced by fetch_directory.
$default_controller
__construct()
ConstructorRuns the route mapping function.
_set_routing()
Set the route mappingThis function determines what should be served based on the URI request, as well as any "routes" that have been set in the routing config file.private void
References set_directory, fetch_directory, set_class, fetch_class, set_method, fetch_method, $route, _validate_request, _set_default_controller, _parse_routes.
_set_default_controller()
Set the default controllerprivate void
References set_class, set_method, _set_request.
Referenced by _set_routing, _set_request.
_set_request($segments=array())
Set the RouteThis function takes an array of URI segments as input, and sets the current class/methodprivate array bool void
References _validate_request, _set_default_controller, set_class, set_method.
Referenced by _set_default_controller, _parse_routes.
_validate_request($segments)
Validates the supplied segments. Attempts to determine the path to the controller.private array array
References set_directory, set_class, set_method, fetch_directory.
Referenced by _set_routing, _set_request.
_parse_routes()
Parse RoutesThis function matches any routes that may exist in the config/routes.php file against the URI to determine if the class/method need to be remapped.private void
References _set_request.
Referenced by _set_routing.
set_class($class)
Set the class namepublic string void
Referenced by _set_routing, _set_default_controller, _set_request, _validate_request, _set_overrides.
fetch_class()
Fetch the current classpublic string
References $class.
Referenced by _set_routing, fetch_method.
set_method($method)
Set the method namepublic string void
References $method.
Referenced by _set_routing, _set_default_controller, _set_request, _validate_request, _set_overrides.
fetch_method()
Fetch the current methodpublic string
References fetch_class, $method.
Referenced by _set_routing.
set_directory($dir)
Set the directory namepublic string void
Referenced by _set_routing, _validate_request, _set_overrides.
fetch_directory()
Fetch the sub-directory (if any) that contains the requested controller classpublic string
References $directory.
Referenced by _set_routing, _validate_request.
_set_overrides($routing)
Set the controller overridespublic array null
References set_directory, set_class, set_method.