CI_Upload
$max_size
$max_width
$max_height
$max_filename
$allowed_types
$file_temp
Referenced by do_xss_clean.
$file_name
Referenced by initialize, do_upload.
$orig_name
$file_type
$file_size
$file_ext
Referenced by do_upload.
$upload_path
$overwrite
$encrypt_name
$is_image
$image_width
$image_height
$image_type
$image_size_str
$error_msg
$mimes
Referenced by mimes_types.
$remove_spaces
$xss_clean
$temp_prefix
$client_name
$_file_name_override
__construct($props=array())
Constructorpublic
References initialize.
initialize($config=array())
Initialize preferences array void
References $config, $method, $file_name.
Referenced by __construct.
do_upload($field= 'userfile')
Perform the file uploadbool
References set_error, validate_upload_path, _file_mime_type, _prep_filename, get_extension, $file_name, is_allowed_filetype, $file_ext, is_allowed_filesize, is_allowed_dimensions, clean_file_name, limit_filename_length, set_filename, do_xss_clean, set_image_properties.
data()
Finalized Data ArrayReturns an associative array containing all of the information related to the upload, allowing the developer easy access in one array.array
References is_image.
set_upload_path($path)
Set Upload Path string void
set_filename($path, $filename)
Set the file nameThis function takes a filename/path as input and looks for the existence of a file with the same name. If found, it will append a number to the end of the filename to avoid overwriting a pre-existing file. string string string
References set_error.
Referenced by do_upload.
set_max_filesize($n)
Set Maximum File Size integer void
References int.
set_max_filename($n)
Set Maximum File Name Length integer void
References int.
set_max_width($n)
Set Maximum Image Width integer void
References int.
set_max_height($n)
Set Maximum Image Height integer void
References int.
set_allowed_types($types)
Set Allowed File Types string void
set_image_properties($path= '')
Set Image PropertiesUses GD to determine the width/height/type of image string void
References is_image.
Referenced by do_upload.
set_xss_clean($flag=FALSE)
Set XSS CleanEnables the XSS flag so that the file that was uploaded will be run through the XSS filter. bool void
is_image()
Validate the imagebool
Referenced by data, set_image_properties, is_allowed_dimensions.
is_allowed_filetype($ignore_mime=FALSE)
Verify that the filetype is allowedbool
References set_error, mimes_types.
Referenced by do_upload.
is_allowed_filesize()
Verify that the file is within the allowed sizebool
Referenced by do_upload.
is_allowed_dimensions()
Verify that the image is within the allowed width/heightbool
References is_image.
Referenced by do_upload.
validate_upload_path()
Validate Upload PathVerifies that it is a valid upload path with proper permissions.bool
References set_error.
Referenced by do_upload.
get_extension($filename)
Extract the file extension string string
Referenced by do_upload.
clean_file_name($filename)
Clean the file name for security string string
Referenced by do_upload.
limit_filename_length($filename, $length)
Limit the File Name Length string string
Referenced by do_upload.
do_xss_clean()
Runs the file through the XSS clean functionThis prevents people from embedding malicious code in their files. I'm not sure that it won't negatively affect certain files in unexpected ways, but so far I haven't found that it causes trouble.void
References $file_temp, $CI, get_instance.
Referenced by do_upload.
set_error($msg)
Set an error message string void
References $CI, get_instance.
Referenced by do_upload, set_filename, is_allowed_filetype, validate_upload_path.
display_errors($open= '< p >', $close= '</p >')
Display the error message string string string
mimes_types($mime)
List of Mime TypesThis is a list of mime types. We use it to validate the "allowed types" set by the developer string string
References $mimes.
Referenced by is_allowed_filetype, _prep_filename.
_prep_filename($filename)
Prep FilenamePrevents possible script execution from Apache's handling of files multiple extensions http://httpd.apache.org/docs/1.3/mod/mod_mime.html#multipleext string string
References mimes_types.
Referenced by do_upload.
_file_mime_type($file)
File MIME typeDetects the (actual) MIME type of the uploaded file, if possible. The input array is expected to be $_FILES[$field] array void
Referenced by do_upload.