CI_Cart
$product_id_rules
$product_name_rules
$CI
$_cart_contents
Referenced by contents.
__construct($params=array())
Shopping Class ConstructorThe constructor loads the Session class, used to store the shopping cart contents.
References get_instance, $config.
insert($items=array())
Insert items into the cart and save it to the session tablepublic array bool
References _insert, _save_cart.
_insert($items=array())
Insertprivate array bool
Referenced by insert.
update($items=array())
Update the cartThis function permits the quantity of a given item to be changed. Typically it is called from the "view cart" page if a user makes changes to the quantity before checkout. That array must contain the product ID and quantity for each item.public array string bool
References _update, _save_cart.
_update($items=array())
Update the cartThis function permits the quantity of a given item to be changed. Typically it is called from the "view cart" page if a user makes changes to the quantity before checkout. That array must contain the product ID and quantity for each item.private array bool
Referenced by update.
_save_cart()
Save the cart array to the session DBprivate bool
Referenced by insert, update.
total()
Cart Totalpublic integer
total_items()
Total ItemsReturns the total item countpublic integer
contents()
Cart ContentsReturns the entire cart arraypublic array
References $_cart_contents.
has_options($rowid= '')
Has optionsReturns TRUE if the rowid passed to this function correlates to an item that has options associated with it.public array
product_options($rowid= '')
Product optionsReturns the an array of options, for a particular product row IDpublic array
format_number($n= '')
Format NumberReturns the supplied number with commas and a decimal point.public integer
destroy()
Destroy the cartEmpties the cart and kills the sessionpublic null