CI_Image_lib
$image_library
$library_path
$dynamic_output
$source_image
Referenced by initialize, explode_name.
$new_image
Referenced by initialize.
$width
Referenced by image_process_gd, image_mirror_gd.
$height
Referenced by image_process_gd, image_process_netpbm, image_mirror_gd.
$quality
Referenced by image_process_imagemagick.
$create_thumb
$thumb_marker
$maintain_ratio
$master_dim
$rotation_angle
$x_axis
Referenced by overlay_watermark, text_watermark.
$y_axis
Referenced by overlay_watermark, text_watermark.
$wm_text
$wm_type
$wm_x_transp
$wm_y_transp
$wm_overlay_path
$wm_font_path
$wm_font_size
Referenced by text_watermark.
$wm_vrt_alignment
$wm_hor_alignment
$wm_padding
Referenced by overlay_watermark, text_watermark.
$wm_hor_offset
$wm_vrt_offset
$wm_font_color
$wm_shadow_color
$wm_shadow_distance
Referenced by text_watermark.
$wm_opacity
$source_folder
Referenced by initialize.
$dest_folder
$mime_type
$orig_width
Referenced by initialize, rotate, image_mirror_gd, image_reproportion.
$orig_height
Referenced by initialize, rotate, image_mirror_gd.
$image_type
Referenced by image_create_gd.
$size_str
$full_src_path
Referenced by image_create_gd, get_image_properties.
$full_dst_path
$create_fnc
$copy_fnc
$error_msg
$wm_use_drop_shadow
$wm_use_truetype
__construct($props=array())
Constructor string void
References initialize.
clear()
Initialize image propertiesResets values in case this class is used in a looppublic void
initialize($props=array())
initialize image preferencespublic array bool
References set_error, $source_image, get_image_properties, $source_folder, $new_image, explode_name, image_reproportion, $orig_width, $orig_height.
Referenced by __construct.
resize()
Image ResizeThis is a wrapper function that chooses the proper resize function based on the protocol specifiedpublic bool
crop()
Image CropThis is a wrapper function that chooses the proper cropping function based on the protocol specifiedpublic bool
rotate()
Image RotateThis is a wrapper function that chooses the proper rotation function based on the protocol specifiedpublic bool
References set_error, $orig_height, $orig_width, image_mirror_gd, image_rotate_gd.
image_process_gd($action= 'resize')
Image Process Using GD/GD2This function will resize or croppublic string bool
References FILE_WRITE_MODE, $width, $height, gd_version, image_create_gd, image_display_gd, image_save_gd.
image_process_imagemagick($action= 'resize')
Image Process Using ImageMagickThis function will resize, crop or rotatepublic string bool
References set_error, $quality, FILE_WRITE_MODE.
image_process_netpbm($action= 'resize')
Image Process Using NetPBMThis function will resize, crop or rotatepublic string bool
References set_error, $height, FILE_WRITE_MODE.
image_rotate_gd()
Image Rotate Using GDpublic bool
References image_create_gd, image_display_gd, image_save_gd, FILE_WRITE_MODE.
Referenced by rotate.
image_mirror_gd()
Create Mirror Image using GDThis function will flip horizontal or verticalpublic bool
References image_create_gd, $width, $orig_width, $height, $orig_height, image_display_gd, image_save_gd, FILE_WRITE_MODE.
Referenced by rotate.
watermark()
Image WatermarkThis is a wrapper function that chooses the type of watermarking based on the specified preference.public string bool
References overlay_watermark, text_watermark.
overlay_watermark()
Watermark - Graphic Versionpublic bool
References set_error, get_image_properties, image_create_gd, $x_axis, $wm_padding, $y_axis, image_display_gd, image_save_gd.
Referenced by watermark.
text_watermark()
Watermark - Text Versionpublic bool
References image_create_gd, set_error, get_image_properties, $wm_font_size, $x_axis, $wm_padding, $y_axis, $wm_shadow_distance, image_display_gd, image_save_gd.
Referenced by watermark.
image_create_gd($path= '', $image_type= '')
Create Image - GDThis simply creates an image resource handle based on the type of image being processedpublic string resource
References $full_src_path, $image_type, set_error.
Referenced by image_process_gd, image_rotate_gd, image_mirror_gd, overlay_watermark, text_watermark.
image_save_gd($resource)
Write image file to disk - GDTakes an image resource as input and writes the file to the specified destinationpublic resource bool
References set_error.
Referenced by image_process_gd, image_rotate_gd, image_mirror_gd, overlay_watermark, text_watermark.
image_display_gd($resource)
Dynamically outputs an imagepublic resource void
Referenced by image_process_gd, image_rotate_gd, image_mirror_gd, overlay_watermark, text_watermark.
image_reproportion()
Re-proportion Image Width/HeightWhen creating thumbs, the desired width/height can end up warping the image due to an incorrect ratio between the full-sized image and the thumb.This function lets us re-proportion the width/height if users choose to maintain the aspect ratio when resizing.public void
References $orig_width.
Referenced by initialize.
get_image_properties($path= '', $return=FALSE)
Get image propertiesA helper function that gets info about the filepublic string mixed
References $full_src_path, set_error.
Referenced by initialize, overlay_watermark, text_watermark.
size_calculator($vals)
Size calculatorThis function takes a known width x height and recalculates it to a new size. Only one new variable needs to be known$props = array( 'width' => $width, 'height' => $height, 'new_width' => 40, 'new_height' => '' );public array array
explode_name($source_image)
Explode source_imageThis is a helper function that extracts the extension from the source_image. This function lets us deal with source_images with multiple periods, like: my.cool.jpg It returns an associative array with two elements: $array['ext'] = '.jpg'; $array['name'] = 'my.cool';public array array
References $source_image.
Referenced by initialize.
gd_loaded()
Is GD Installed?public bool
gd_version()
Get GD versionpublic mixed
Referenced by image_process_gd.
set_error($msg)
Set error messagepublic string void
References $CI, get_instance.
Referenced by initialize, rotate, image_process_imagemagick, image_process_netpbm, overlay_watermark, text_watermark, image_create_gd, image_save_gd, get_image_properties.
display_errors($open= '< p >', $close= '</p >')
Show error messagespublic string string