CI_DB_result
$conn_id
$result_id
$result_array
Referenced by result_array, CI_DB_oci8_result\result_array.
$result_object
Referenced by custom_result_object, result_object.
$custom_result_object
$current_row
Referenced by custom_row_object, row_object, row_array, next_row, previous_row.
$num_rows
Referenced by num_rows, CI_DB_oci8_result\num_rows.
$row_data
result($type= 'object')
Query result. Acts as a wrapper function for the following functions.public string can be "object" or "array" mixed either a result object or array
References result_array, result_object, custom_result_object.
Referenced by first_row, last_row, next_row, previous_row.
custom_result_object($class_name)
Custom query result. class_name A string that represents the type of object you want back array of objects
References num_rows, _data_seek, $result_object, _fetch_object.
Referenced by result, custom_row_object.
result_object()
Query result. "object" version.public object
References $result_object, num_rows, _data_seek, _fetch_object.
Referenced by result, row_object.
result_array()
Query result. "array" version.public array
References $result_array, num_rows, _data_seek, _fetch_assoc.
Referenced by result, row_array.
row($n=0, $type= 'object')
Query result. Acts as a wrapper function for the following functions.public string string can be "object" or "array" mixed either a result object or array
References row_array, row_object, custom_row_object.
set_row($key, $value=NULL)
Assigns an item into a particular column slotpublic object
References row_array.
custom_row_object($n, $type)
Returns a single result row - custom object versionpublic object
References custom_result_object, $current_row.
Referenced by row.
row_object($n=0)
Returns a single result row - object versionpublic object
References result_object, $current_row.
Referenced by row.
row_array($n=0)
Returns a single result row - array versionpublic array
References result_array, $current_row.
Referenced by row, set_row.
first_row($type= 'object')
Returns the "first" rowpublic object
References result.
last_row($type= 'object')
Returns the "last" rowpublic object
References result.
next_row($type= 'object')
Returns the "next" rowpublic object
References result, $current_row.
previous_row($type= 'object')
Returns the "previous" rowpublic object
References result, $current_row.
num_rows()
The following functions are normally overloaded by the identically named methods in the platform-specific driver except when query caching is used. When caching is enabled we do not load the other driver. These functions are primarily here to prevent undefined function errors when a cached result object is in use. They are not otherwise fully operational due to the unavailability of the database resource IDs with cached results.
References $num_rows.
Referenced by custom_result_object, result_object, result_array.
num_fields()
list_fields()
field_data()
free_result()
_data_seek()
Referenced by custom_result_object, result_object, result_array.
_fetch_assoc()
Referenced by result_array.
_fetch_object()
Referenced by custom_result_object, result_object.