CI_Output
$final_output
Referenced by get_output, _display.
$cache_expiration
$headers
$mime_types
$enable_profiler
$_zlib_oc
$_profiler_sections
$parse_exec_vars
__construct()
Constructor
References $mimes.
get_output()
Get OutputReturns the current output stringpublic string
References $final_output.
set_output($output)
Set OutputSets the output stringpublic string void
append_output($output)
Append OutputAppends data onto the output stringpublic string void
set_header($header, $replace=TRUE)
Set HeaderLets you set a server header which will be outputted with the final display.Note: If a file is cached, headers will not be sent. We need to figure out how to permit header data to be saved with the cache data...public string bool void
set_content_type($mime_type)
Set Content Type Headerpublic string extension of the file we're outputting void
set_status_header($code=200, $text= '')
Set HTTP Status Header moved to Common procedural functions in 1.7.2public int the status code string void
enable_profiler($val=TRUE)
Enable/disable Profilerpublic bool void
Referenced by _display.
set_profiler_sections($sections)
Set Profiler SectionsAllows override of default / config settings for Profiler section displaypublic array void
cache($time)
Set Cachepublic integer void
_display($output= '')
Display OutputAll "view" data is automatically put into this variable by the controller class:$this->final_outputThis function sends the finalized output data to the browser along with any server headers and profile data. It also stops the benchmark timer so the page rendering speed and memory usage can be shown.public string mixed
References $BM, $CFG, $CI, get_instance, $final_output, _write_cache, enable_profiler.
Referenced by _display_cache.
_write_cache($output)
Write a Cache Filepublic string void
References $CI, get_instance, if, FOPEN_WRITE_CREATE_DESTRUCTIVE, FILE_WRITE_MODE.
Referenced by _display.
_display_cache(&$CFG, &$URI)
Update/serve a cached filepublic object config class object uri class void
References $CFG, $URI, FOPEN_READ, _display.