CI_Loader
$_ci_ob_level
$_ci_view_paths
Referenced by add_package_path.
$_ci_library_paths
$_ci_model_paths
Referenced by get_package_paths.
$_ci_helper_paths
$_base_classes
$_ci_cached_vars
$_ci_classes
$_ci_loaded_files
$_ci_models
$_ci_helpers
$_ci_varmap
__construct()
ConstructorSets the path to the view files and gets the initial output buffering level
References BASEPATH.
initialize()
Initialize the LoaderThis method is called once in CI_Controller. array object
References is_loaded.
is_loaded($class)
Is LoadedA utility function to test if a class is in the self::$_ci_classes array. This function returns the object name if the class tested for is loaded, and returns FALSE if it isn't.It is mainly used in the form_helper -> _get_validation_object() string class being checked for mixed class object name on the CI SuperObject or FALSE
References $class.
Referenced by initialize.
library($library= '', $params=NULL, $object_name=NULL)
Class LoaderThis function lets users load and instantiate classes. It is designed to be called from a user's app controllers. string the name of the class mixed the optional parameters string an optional object name void
References $class, _ci_load_class.
Referenced by driver.
model($model, $name= '', $db_conn=FALSE)
Model LoaderThis function lets users load and instantiate models. string the name of the class string name for the model bool database connection void
References $CI, get_instance.
database($params= '', $return=FALSE, $active_record=NULL)
Database Loader string the DB credentials bool whether to return the DB object bool whether to enable active record (this allows us to override the config setting) object
References $CI, get_instance, $active_record, BASEPATH, DB.
Referenced by dbutil, dbforge.
dbutil()
Load the Utilities Classstring
References database, $CI, get_instance, BASEPATH, $class.
dbforge()
Load the Database Forge Classstring
References database, $CI, get_instance, BASEPATH, $class.
view($view, $vars=array(), $return=FALSE)
Load ViewThis function is used to load a "view" file. It has three parameters: The name of the "view" file to be included.An associative array of data to be extracted for use in the view.TRUE/FALSE - whether to return the data or load it. In some cases it's advantageous to be able to return data so that a developer can process it in some way. string array bool void
References _ci_load, _ci_object_to_array.
file($path, $return=FALSE)
Load FileThis is a generic file loader string bool string
References _ci_load.
vars($vars=array(), $val= '')
Set VariablesOnce variables are set they become available within the controller class and its "view" files. array string void
References _ci_object_to_array.
get_var($key)
Get VariableCheck if a variable is set and retrieve it. array void
helper($helpers=array())
Load HelperThis function loads the specified helper file. mixed void
References _ci_prep_filename, BASEPATH.
Referenced by helpers.
helpers($helpers=array())
Load HelpersThis is simply an alias to the above function in case the user has written the plural form of this function. array void
References helper.
language($file=array(), $lang= '')
Loads a language file array string void
References $CI, get_instance, $lang.
config($file= '', $use_sections=FALSE, $fail_gracefully=FALSE)
Loads a config file string bool bool void
References $CI, get_instance.
driver($library= '', $params=NULL, $object_name=NULL)
DriverLoads a driver library string the name of the class mixed the optional parameters string an optional object name void
References BASEPATH, library.
add_package_path($path, $view_cascade=TRUE)
Add Package PathPrepends a parent path to the library, model, helper, and config path arrays string boolean void
References $_ci_view_paths, $config, _ci_get_component.
get_package_paths($include_base=FALSE)
Get Package PathsReturn a list of all package paths, by default it will ignore BASEPATH. string void
References $_ci_model_paths.
remove_package_path($path= '', $remove_config_path=TRUE)
Remove Package PathRemove a path from the library, model, and helper path arrays if it exists If no path is provided, the most recently added path is removed. type bool type
References $config, _ci_get_component, BASEPATH.
_ci_load($_ci_data)
LoaderThis function is used to load views and files. Variables are prefixed with ci to avoid symbol collision with variables made available to view files array void
References foreach, get_instance.
Referenced by view, file.
_ci_load_class($class, $params=NULL, $object_name=NULL)
Load classThis function loads the requested class. string the item that is being loaded mixed any additional parameters string an optional object name void
References $class, BASEPATH, $CI, get_instance, _ci_init_class.
Referenced by library.
_ci_init_class($class, $prefix= '', $config=FALSE, $object_name=NULL)
Instantiates a class string string bool string an optional object name null
References $config, _ci_get_component, $class, $CI, get_instance.
Referenced by _ci_load_class.
_ci_object_to_array($object)
Object to ArrayTakes an object as input and converts the class variables to array key/vals object array
Referenced by view, vars.
& _ci_get_component($component)
Get a reference to a specific library or model string bool
References $CI, get_instance.
Referenced by add_package_path, remove_package_path, _ci_init_class.
_ci_prep_filename($filename, $extension)
Prep filenameThis function preps the name of various items to make loading them more reliable. mixed string array
Referenced by helper.
_ci_autoloader()
AutoloaderThe config/autoload.php file contains an array that permits sub-systems, libraries, and helpers to be loaded automatically. array void