CI_Encrypt
$CI
Referenced by get_key.
$encryption_key
Referenced by get_key.
$_hash_type
$_mcrypt_exists
$_mcrypt_cipher
Referenced by _get_cipher.
$_mcrypt_mode
Referenced by _get_mode.
__construct()
ConstructorSimply determines whether the mcrypt library exists.
References get_instance.
get_key($key= '')
Fetch the encryption keyReturns it as MD5 in order to have an exact-length 128 bit key. Mcrypt is sensitive to keys that are not the correct lengthpublic string string
References $encryption_key, $CI, get_instance.
Referenced by encode, decode, encode_from_legacy.
set_key($key= '')
Set the encryption keypublic string void
encode($string, $key= '')
EncodeEncodes the message string using bitwise XOR encoding. The key is combined with a random hash, and then it too gets converted using XOR. The whole thing is then run through mcrypt (if supported) using the randomized key. The end result is a double-encrypted message string that is randomized with each call to this function, even if the supplied message and key are the same.public string the string to encode string the key string
References get_key, mcrypt_encode, _xor_encode.
decode($string, $key= '')
DecodeReverses the above processpublic string string string
References get_key, mcrypt_decode, _xor_decode.
encode_from_legacy($string, $legacy_mode=MCRYPT_MODE_ECB, $key= '')
Encode from LegacyTakes an encoded string from the original Encryption class algorithms and returns a newly encoded string using the improved method added in 2.0.0 This allows for backwards compatibility and a method to transition to the new encryption algorithms.For more details, see http://codeigniter.com/user_guide/installation/upgrade_200.html#encryptionpublic string int (mcrypt mode constant) string string
References _get_mode, set_mode, get_key, mcrypt_decode, _xor_decode, mcrypt_encode.
_xor_encode($string, $key)
XOR EncodeTakes a plain-text string and key as input and generates an encoded bit-string using XORprivate string string string
References hash, _xor_merge.
Referenced by encode.
_xor_decode($string, $key)
XOR DecodeTakes an encoded string and key as input and generates the plain-text original messageprivate string string string
References _xor_merge.
Referenced by decode, encode_from_legacy.
_xor_merge($string, $key)
XOR key + string CombinerTakes a string and key as input and computes the difference using XORprivate string string string
References hash.
Referenced by _xor_encode, _xor_decode.
mcrypt_encode($data, $key)
Encrypt using Mcryptpublic string string string
References _get_cipher, _get_mode, _add_cipher_noise.
Referenced by encode, encode_from_legacy.
mcrypt_decode($data, $key)
Decrypt using Mcryptpublic string string string
References _remove_cipher_noise, _get_cipher, _get_mode.
Referenced by decode, encode_from_legacy.
_add_cipher_noise($data, $key)
Adds permuted noise to the IV + encrypted data to protect against Man-in-the-middle attacks on CBC mode ciphers http://www.ciphersbyritter.com/GLOSSARY.HTM#IVFunction descriptionprivate string string string
References hash.
Referenced by mcrypt_encode.
_remove_cipher_noise($data, $key)
Removes permuted noise from the IV + encrypted data, reversing _add_cipher_noise()Function descriptionpublic type type
References hash.
Referenced by mcrypt_decode.
set_cipher($cipher)
Set the Mcrypt Cipherpublic constant string
set_mode($mode)
Set the Mcrypt Modepublic constant string
Referenced by encode_from_legacy.
_get_cipher()
Get Mcrypt cipher Valueprivate string
References $_mcrypt_cipher.
Referenced by mcrypt_encode, mcrypt_decode.
_get_mode()
Get Mcrypt Mode Valueprivate string
References $_mcrypt_mode.
Referenced by encode_from_legacy, mcrypt_encode, mcrypt_decode.
set_hash($type= 'sha1')
Set the Hash typepublic string string
hash($str)
Hash encode a stringpublic string string
References sha1.
Referenced by _xor_encode, _xor_merge, _add_cipher_noise, _remove_cipher_noise.
sha1($str)
Generate an SHA1 Hashpublic string string
References BASEPATH.
Referenced by hash.