CI_Form_validation
$CI
$_field_data
$_config_rules
$_error_array
$_error_messages
$_error_prefix
Referenced by error, error_string.
$_error_suffix
Referenced by error, error_string.
$error_string
$_safe_form_data
__construct($rules=array())
Constructor
References get_instance.
set_rules($field, $label= '', $rules= '')
Set RulesThis function takes an array of field names and validation rules as input, validates the info, and stores itpublic mixed string void
Referenced by run.
set_message($lang, $val= '')
Set Error MessageLets users set their own error messages on the fly. Note: The key name has to match the function name that it corresponds to.public string string string
References $lang.
set_error_delimiters($prefix= '< p >', $suffix= '</p >')
Set The Error DelimiterPermits a prefix/suffix to be added to each error messagepublic string string void
error($field= '', $prefix= '', $suffix= '')
Get Error MessageGets the error message associated with a particular fieldpublic string the field name void
References $_error_prefix, $_error_suffix.
error_string($prefix= '', $suffix= '')
Error StringReturns the error messages as a string, wrapped in the error delimiterspublic string string str
References $_error_prefix, $_error_suffix.
run($group= '')
Run the ValidatorThis function does all the work.public bool
References set_rules, _reduce_array, _execute, _reset_post_array.
set_value($field= '', $default= '')
Get the value from a formPermits you to repopulate a form field with the value it was submitted with, or, if that value doesn't exist, with the defaultpublic string the field name string void
set_select($field= '', $value= '', $default=FALSE)
Set SelectEnables pull-down lists to be set to the value the user selected in the event of an errorpublic string string string
set_radio($field= '', $value= '', $default=FALSE)
Set RadioEnables radio buttons to be set to the value the user selected in the event of an errorpublic string string string
set_checkbox($field= '', $value= '', $default=FALSE)
Set CheckboxEnables checkboxes to be set to the value the user selected in the event of an errorpublic string string string
required($str)
Requiredpublic string bool
regex_match($str, $regex)
Performs a Regular Expression match test.public string regex bool
matches($str, $field)
Match one field to anotherpublic string field bool
is_unique($str, $field)
Match one field to anotherpublic string field bool
min_length($str, $val)
Minimum Lengthpublic string value bool
max_length($str, $val)
Max Lengthpublic string value bool
exact_length($str, $val)
Exact Lengthpublic string value bool
valid_email($str)
Valid Emailpublic string bool
Referenced by valid_emails.
valid_emails($str)
Valid Emailspublic string bool
References valid_email.
valid_ip($ip, $which= '')
Validate IP Addresspublic string string "ipv4" or "ipv6" to validate a specific ip format string
alpha($str)
Alphapublic string bool
alpha_numeric($str)
Alpha-numericpublic string bool
alpha_dash($str)
Alpha-numeric with underscores and dashespublic string bool
numeric($str)
Numericpublic string bool
is_numeric($str)
Is Numericpublic string bool
Referenced by greater_than, less_than.
integer($str)
Integerpublic string bool
decimal($str)
Decimal numberpublic string bool
greater_than($str, $min)
Greather thanpublic string bool
References is_numeric.
less_than($str, $max)
Less thanpublic string bool
References is_numeric.
is_natural($str)
Is a Natural number (0,1,2,3, etc.)public string bool
is_natural_no_zero($str)
Is a Natural number, but not a zero (1,2,3, etc.)public string bool
valid_base64($str)
Valid Base64Tests a string for characters outside of the Base64 alphabet as defined by RFC 2045 http://www.faqs.org/rfcs/rfc2045public string bool
prep_for_form($data= '')
Prep data for formThis function allows HTML to be safely shown in a form. Special characters are converted.public string string
Referenced by _reset_post_array.
prep_url($str= '')
Prep URLpublic string string
strip_image_tags($str)
Strip Image Tagspublic string string
xss_clean($str)
XSS Cleanpublic string string
encode_php_tags($str)
Convert PHP tags to entitiespublic string string
_reduce_array($array, $keys, $i=0)
Traverse a multidimensional $_POST array index until the data is foundprivate array array integer mixed
Referenced by run.
_reset_post_array()
Re-populate the _POST array with our finalized and processed dataprivate null
References prep_for_form.
Referenced by run.
_execute($row, $rules, $postdata=NULL, $cycles=0)
Executes the Validation routinesprivate array array mixed integer mixed
References _translate_fieldname.
Referenced by run.
_translate_fieldname($fieldname)
Translate a field nameprivate string the field name string
Referenced by _execute.