CI_URI
$keyval
$uri_string
Referenced by uri_string.
$segments
Referenced by _uri_to_assoc, segment_array.
$rsegments
Referenced by rsegment_array.
__construct()
ConstructorSimply globalizes the $RTR object. The front loads the Router class early on so it's not available normally as other classes are.public
_fetch_uri_string()
Get the URI Stringprivate string
References or, _set_uri_string, uri_string.
_set_uri_string($str)
Set the URI Stringpublic string string
References uri_string.
Referenced by _fetch_uri_string.
_filter_uri($str)
Filter segments for malicious charactersprivate string string
Referenced by _explode_segments.
_remove_url_suffix()
Remove the suffix from the URL if neededprivate void
References uri_string.
_explode_segments()
Explode the URI Segments. The individual segments will be stored in the $this->segments array.private void
References uri_string, _filter_uri.
_reindex_segments()
Re-index SegmentsThis function re-indexes the $this->segment array so that it starts at 1 rather than 0. Doing so makes it simpler to use functions like $this->uri->segment(n) since there is a 1:1 relationship between the segment array and the actual segments.private void
segment($n, $no_result=FALSE)
Fetch a URI SegmentThis function returns the URI segment based on the number provided.public integer bool string
rsegment($n, $no_result=FALSE)
Fetch a URI "routed" SegmentThis function returns the re-routed URI segment (assuming routing rules are used) based on the number provided. If there is no routing this function returns the same result as $this->segment()public integer bool string
uri_to_assoc($n=3, $default=array())
Generate a key value pair from the URI stringThis function generates and associative array of URI data starting at the supplied segment. For example, if this is your URI:example.com/user/search/name/joe/location/UK/gender/maleYou can use this function to generate an array with this prototype:array ( name => joe location => UK gender => male )public integer the starting segment number array an array of default values array
References _uri_to_assoc.
ruri_to_assoc($n=3, $default=array())
Identical to above only it uses the re-routed segment arraypublic integer the starting segment number array an array of default values array
References _uri_to_assoc.
_uri_to_assoc($n=3, $default=array(), $which= 'segment')
Generate a key value pair from the URI string or Re-routed URI stringprivate integer the starting segment number array an array of default values string which array we should use array
References $segments.
Referenced by uri_to_assoc, ruri_to_assoc.
assoc_to_uri($array)
Generate a URI string from an associative arraypublic array an associative array of key/values array
slash_segment($n, $where= 'trailing')
Fetch a URI Segment and add a trailing slashpublic integer string string
References _slash_segment.
slash_rsegment($n, $where= 'trailing')
Fetch a URI Segment and add a trailing slashpublic integer string string
References _slash_segment.
_slash_segment($n, $where= 'trailing', $which= 'segment')
Fetch a URI Segment and add a trailing slash - helper functionprivate integer string string string
Referenced by slash_segment, slash_rsegment.
segment_array()
Segment Arraypublic array
References $segments.
rsegment_array()
Routed Segment Arraypublic array
References $rsegments.
Referenced by ruri_string.
total_segments()
Total number of segmentspublic integer
total_rsegments()
Total number of routed segmentspublic integer
uri_string()
Fetch the entire URI stringpublic string
References $uri_string.
Referenced by _fetch_uri_string, _set_uri_string, _remove_url_suffix, _explode_segments.
ruri_string()
Fetch the entire Re-routed URI stringpublic string
References rsegment_array.
_detect_uri()
Detects the URIThis function will detect the URI automatically and fix the query string if necessary.private string
_parse_cli_args()
Parse cli argumentsTake each command line argument and assume it is a URI segment.private string