CI_Calendar
$CI
$lang
$local_time
$template
$start_day
Referenced by generate.
$month_type
$day_type
Referenced by get_day_names.
$show_next_prev
$next_prev_url
__construct($config=array())
ConstructorLoads the calendar language file and sets the default time reference
References get_instance, $config, initialize.
initialize($config=array())
Initialize the user preferencesAccepts an associative array as input, containing display preferencespublic array config preferences void
References $config.
Referenced by __construct.
generate($year= '', $month= '', $data=array())
Generate the calendarpublic integer the year integer the month array the data to be shown in the calendar cells string
References adjust_date, get_total_days, $start_day, parse_template, get_month_name, get_day_names.
get_month_name($month)
Get Month NameGenerates a textual month name based on the numeric month provided.public integer the month string
Referenced by generate.
get_day_names($day_type= '')
Get Day NamesReturns an array of day names (Sunday, Monday, etc.) based on the type. Options: long, short, abrevpublic string array
References $day_type.
Referenced by generate.
adjust_date($month, $year)
Adjust DateThis function makes sure that we have a valid month/year. For example, if you submit 13 as the month, the year will increment and the month will become January.public integer the month integer the year array
Referenced by generate.
get_total_days($month, $year)
Total days in a given monthpublic integer the month integer the year integer
Referenced by generate.
default_template()
Set Default Template DataThis is used in the event that the user has not created their own templatepublic array
Referenced by parse_template.
parse_template()
Parse TemplateHarvests the data within the template {pseudo-variables} used to display the calendarpublic void
References default_template.
Referenced by generate.